apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: museum-wayang-tales-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gebyginting/Website_Museum_Wayang_Tales.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: museum-wayang-tales

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
